//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_tip_reparatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_tip_reparatie()
        {
            this.oferta_tip_reparatie = new HashSet<oferta_tip_reparatie>();
            this.produs = new HashSet<produ>();
        }
    
        public int id { get; set; }
        public string denumire { get; set; }
        public string descriere { get; set; }
        public int timp_necesar_max { get; set; }
        public int timp_necesar_min { get; set; }
        public decimal pret { get; set; }
        public bool activ { get; set; }
        public int id_catalog_servicii { get; set; }
    
        public virtual catalog_servicii catalog_servicii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferta_tip_reparatie> oferta_tip_reparatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produ> produs { get; set; }
    }
}
