//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_servicii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_servicii()
        {
            this.catalog_tip_reparatie = new HashSet<catalog_tip_reparatie>();
            this.oferte_servicii = new HashSet<oferte_servicii>();
        }
    
        public int id { get; set; }
        public string denumire { get; set; }
        public string descriere { get; set; }
        public Nullable<decimal> discount { get; set; }
        public bool activ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_tip_reparatie> catalog_tip_reparatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferte_servicii> oferte_servicii { get; set; }
    }
}
