//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Contacts = new HashSet<Contact>();
            this.oferte_servicii = new HashSet<oferte_servicii>();
            this.vehiculs = new HashSet<vehicul>();
        }
    
        public int id { get; set; }
        public string nume { get; set; }
        public string prenume { get; set; }
        public string denumire_companie { get; set; }
        public string adresa { get; set; }
        public string contact { get; set; }
        public string cont_bancar { get; set; }
        public string CIF { get; set; }
        public string nr_reg_com { get; set; }
        public string detalii { get; set; }
        public System.DateTime data_inregistrare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferte_servicii> oferte_servicii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicul> vehiculs { get; set; }
    }
}
