//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.oferte_servicii = new HashSet<oferte_servicii>();
        }
    
        public int Contact_Id { get; set; }
        public Nullable<System.DateTime> Data_Inreg { get; set; }
        public string Detalii { get; set; }
        public Nullable<int> Tip_Contact_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Programare_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual programare programare { get; set; }
        public virtual Tip_Contact Tip_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferte_servicii> oferte_servicii { get; set; }
    }
}
