//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceAutoDBEntities : DbContext
    {
        public ServiceAutoDBEntities()
            : base("name=ServiceAutoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Angajat> Angajats { get; set; }
        public virtual DbSet<catalog_servicii> catalog_servicii { get; set; }
        public virtual DbSet<catalog_tip_reparatie> catalog_tip_reparatie { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<oferte_servicii> oferte_servicii { get; set; }
        public virtual DbSet<pozitie_angajat> pozitie_angajat { get; set; }
        public virtual DbSet<produ> produs { get; set; }
        public virtual DbSet<programare> programares { get; set; }
        public virtual DbSet<Punct_Lucru_Service> Punct_Lucru_Service { get; set; }
        public virtual DbSet<Tip_Contact> Tip_Contact { get; set; }
        public virtual DbSet<vehicul> vehiculs { get; set; }
        public virtual DbSet<oferta_tip_reparatie> oferta_tip_reparatie { get; set; }
    }
}
