//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferte_servicii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oferte_servicii()
        {
            this.oferta_tip_reparatie = new HashSet<oferta_tip_reparatie>();
        }
    
        public int id { get; set; }
        public string descriere { get; set; }
        public Nullable<decimal> pret { get; set; }
        public System.DateTime data_inregistrare { get; set; }
        public int id_client { get; set; }
        public Nullable<int> id_contact { get; set; }
        public int id_catalog_servicii { get; set; }
    
        public virtual catalog_servicii catalog_servicii { get; set; }
        public virtual Client Client { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferta_tip_reparatie> oferta_tip_reparatie { get; set; }
    }
}
