//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta_tip_reparatie
    {
        public int id { get; set; }
        public Nullable<decimal> pret_tip_reparatie { get; set; }
        public int id_oferte_servicii { get; set; }
        public int id_catalog_tip_reparatie { get; set; }
    
        public virtual catalog_tip_reparatie catalog_tip_reparatie { get; set; }
        public virtual oferte_servicii oferte_servicii { get; set; }
    }
}
