//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produ()
        {
            this.catalog_tip_reparatie = new HashSet<catalog_tip_reparatie>();
        }
    
        public int id { get; set; }
        public string denumire { get; set; }
        public string serie { get; set; }
        public string compatibilitate { get; set; }
        public string original_sau_aftermarket { get; set; }
        public string descriere { get; set; }
        public Nullable<decimal> cost_achizitie { get; set; }
        public Nullable<decimal> cost_vanzare { get; set; }
        public Nullable<int> discount_maxim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catalog_tip_reparatie> catalog_tip_reparatie { get; set; }
    }
}
