//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicul
    {
        public int id { get; set; }
        public string serie_sasiu { get; set; }
        public string nr_inmatriculare { get; set; }
        public Nullable<int> an_fabricatie { get; set; }
        public string detalii { get; set; }
        public System.DateTime data_inregistrare { get; set; }
        public Nullable<int> id_client { get; set; }
        public string tip_vehicul { get; set; }
        public string producator { get; set; }
        public string model { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
